tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      echo "Exported HMR_HOST, about to Start Dev Server" 
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser    
